project:
  type: website

website:
  title: "molviewspec-live"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    grid:
      sidebar-width: "150px"
      margin-width: "150px"
      body-width: "1200px"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

resources:
  - "packages"
